version: '3'

services:
    reverseproxy:
        build: ./reverseproxy
        image: reverseproxy
        ports:
            - 80:80
        restart: always

networks:
    default:
        external:
            name: nginx-proxy
